[project]
name = "fastapi-crud"
version = "0.1.0"
description = "Example of a FastAPI CRUD app"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
