"""Add is_deleted column to User, Post, Comment, and Tag

Revision ID: 4c864611810d
Revises: f13c515d42e1
Create Date: 2025-10-30 19:40:55.198894

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c864611810d"
down_revision: Union[str, Sequence[str], None] = "f13c515d42e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("posts", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("tags", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_deleted")
    op.drop_column("tags", "is_deleted")
    op.drop_column("posts", "is_deleted")
    op.drop_column("comments", "is_deleted")
    # ### end Alembic commands ###
