"""Fix updated_at column

Revision ID: dcd16f90fbbe
Revises: f10149bd53f7
Create Date: 2025-11-03 23:11:52.425729

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dcd16f90fbbe"
down_revision: Union[str, Sequence[str], None] = "f10149bd53f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("post_id", sa.Integer(), nullable=False))
    op.alter_column(
        "comments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the record was updated",
        existing_comment="Timestamp when the record was created",
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.create_index(op.f("ix_comments_post_id"), "comments", ["post_id"], unique=False)
    op.create_foreign_key(
        "fk_comments_post_id_posts",
        "comments",
        "posts",
        ["post_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column(
        "posts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the record was updated",
        existing_comment="Timestamp when the record was created",
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "tags",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the record was updated",
        existing_comment="Timestamp when the record was created",
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the record was updated",
        existing_comment="Timestamp when the record was created",
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the record was created",
        existing_comment="Timestamp when the record was updated",
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "tags",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the record was created",
        existing_comment="Timestamp when the record was updated",
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.alter_column(
        "posts",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the record was created",
        existing_comment="Timestamp when the record was updated",
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_constraint("fk_comments_post_id_posts", "comments", type_="foreignkey")
    op.drop_index(op.f("ix_comments_post_id"), table_name="comments")
    op.alter_column(
        "comments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the record was created",
        existing_comment="Timestamp when the record was updated",
        existing_nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP"),
    )
    op.drop_column("comments", "post_id")
    # ### end Alembic commands ###
